# Generated by Django 4.1.13 on 2024-01-30 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_tasks_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks_model',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='task.users_model'),
        ),
    ]
